name: so_flutter
description: A wrapper around Flutter's App concepts. This package provides a small set of helper classes for quickly building Flutter applications based on Material design.
version: 0.3.10
homepage: https://github.com/syampillai/so_flutter

environment:
  sdk: '>=3.0.0 <=3.5.4'
  flutter: '>=3.24.4'

dependencies:
  flutter:
    sdk: flutter

  so_money: ^0.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
