name: so_flutter
description: A wrapper around Flutter's App concepts. This package provides is a small set of helper classes for quickly building Flutter applications based on Material design.
version: 0.3.3
homepage: https://github.com/syampillai/so_flutter

environment:
  sdk: '>=3.0.0 <=3.1.5'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  so_money: ^0.0.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
