name: so_flutter
description: A wrapper around Flutter's App concepts. This package provides a small set of helper classes for quickly building Flutter applications based on Material design.
version: 0.3.11
homepage: https://github.com/syampillai/so_flutter

environment:
  sdk: '>=3.0.0 <=3.7.0'
  flutter: '>=3.29.1'

dependencies:
  flutter:
    sdk: flutter

  so_money: ^0.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
